# <center> R Basic Quickstart </center>

In [1]:
## assign value to a variable  (<- or = syntaxes)

x <- 1
# or
y = 2

print(x)
print(y)

[1] 1
[1] 2


#### `c()` command - creating vectors

In [2]:
## Create a vector of values

x_vec = c(1,2,3,4,5)  ## c() command is to concatenate the numericals and make it into a list/array
# or
y_vec = c(1:5)  ## this returns the same as x_vec, but this way makes it efficient

print(x_vec)
print(y_vec)

[1] 1 2 3 4 5
[1] 1 2 3 4 5


### `list()` command - list of values

In [3]:
## Create a list of values - meaning we have a list combination of characters, numericals, and even lists/arrays
## use the list() command, making it into a list of values

x_list = list(1,"two",x_vec,4,5)
print(x_list)  ## Notice that it prints with its assigned index number! Very informative!

[[1]]
[1] 1

[[2]]
[1] "two"

[[3]]
[1] 1 2 3 4 5

[[4]]
[1] 4

[[5]]
[1] 5



In [4]:
## Call an element from the vector

x_vec[3]

## Call a list of elements from the vector

x_vec[c(3,4)]  ## Returns list of 2 elements with indices 3 and 4

## Call a single element from the list

x_list[[3]] ## Notice this was the assigned index number when we printed the x_list in the previous cell.

[1] 3

[1] 3 4

[1] 1 2 3 4 5

### `mean()` command

In [5]:
## Compute the mean, using the mean() command, of the numbers in x_vec

mean(x_vec) ## Recall that x_vec contains only concated numericals 

[1] 3

In [6]:
## To get help about the usage of a term, within R.

?plot  ## A pop-up will appear

# <center><font color=blue> Matrices </font></center>

### `matrix()` command

In [26]:
## Create a matrix, using the matrix() command

x_mat = matrix(0,nrow=3,ncol=2) ## this means all entries in the matrix is 0, #rows is 3, #columns is 2
print(x_mat)  ## Notice it gives us the assigned rows(m) and columns(n) index!!!

     [,1] [,2]
[1,]    0    0
[2,]    0    0
[3,]    0    0


In [27]:
x_mat ## Notice the difference if you don't use the print() command

[,1] [,2]
[1,] 0    0   
[2,] 0    0   
[3,] 0    0

### `t()` transpose command

In [28]:
## Transpose the matrix - means convert entries from rows to columns and columns to rows
## use the t() function
t(x_mat)

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0

In [29]:
## Return the element in row 1 and column 2

x_mat[1,2]

## Return all elements in row 1 and column 2

x_mat[c(1,2)]

## Return all elements in row 1 

x_mat[1,]

[1] 0

[1] 0 0

[1] 0 0

In [30]:
## Let's start filling up the matrix

# But first, let's get the number of rows and columns in the matrix
dm = dim(x_mat)  # dim() command 'dimensions' this gives the list of # rows and # columns in the matrix
print(dm)  # the first number is # Rows and the second number is # Columns

# Before adding values matrix
print(x_mat)

# After adding values in the entire first column the matrix
x_mat[,1] = c(1,2,3)  # This means we are assigning the entire first column in the matrix with these numericals
print(x_mat)

# After adding values in the entire second row, NOTE: ANY CHANGES WILL OVERWRITE THE MOST RECENT CHANGES
x_mat[2,] = c(4,5) ## Notice the entire second row got updated
print(x_mat)

[1] 3 2
     [,1] [,2]
[1,]    0    0
[2,]    0    0
[3,]    0    0
     [,1] [,2]
[1,]    1    0
[2,]    2    0
[3,]    3    0
     [,1] [,2]
[1,]    1    0
[2,]    4    5
[3,]    3    0


# <font color=red> BEWARE!! running the cells again and again will update the matrix! </font>

### `rownames()` and `colnames()` commands

In [31]:
## Assigning names for rows and columns and addressing/calling them by name

# Before name changing:
x_mat

# After naming changing:  rownames() and colnames() commands
rownames(x_mat) = c("row1","row2","row3")
colnames(x_mat) = c("col1","col2")
x_mat

# Call by name
x_mat[,"col1"]

[,1] [,2]
[1,] 1    0   
[2,] 4    5   
[3,] 3    0

col1 col2
row1 1    0   
row2 4    5   
row3 3    0

row1 row2 row3 
   1    4    3

### `colSums()` and `rowSums()` commands - arithmetic 

In [32]:
## Arithmetics!  colSums() and rowSums() commands

colSums(x_mat) # Sum all the numbers in the column
rowSums(x_mat) # Sum all the numbers in the row
## All will be returned as a list

col1 col2 
   8    5

row1 row2 row3 
   1    9    3

### `cbind(vector1,vector2,...,vectorN)` - meaning `column bind` method
#### <font color=olive>Binding vectors as columns to create a matrix or add columns to an existing matrix</font>

In [35]:
# Manual

cbind(c(1,2,3),c(4,5,6))  ## Stacking up vectors as columns

# Efficient, already naming the columns
vector1 = c(1,2,3) # or c(1:3)
vector2 = c(4,5,6) # or c(4:6)

cbind(vector1,vector2)


[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

vector1 vector2
[1,] 1       4      
[2,] 2       5      
[3,] 3       6

### `rbind(vector1,vector2,...,vectorN)` - meaning `row bind` method
#### <font color=olive>Binding vectors as rows to create a matrix or add rows to an existing matrix</font>

In [1]:
rbind(c(1:3),c(4:6),c(7:9))  ## You stack up the vectors as rows

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

### Another way of creating a matrix, via `dim()` command

In [46]:
# Convert a vector to a matrix using dim()

x = c(1:6)
print(x) 
dim(x) # What it looks like before proceeding

dim(x) = c(2,3)  # Recall, dim() returns two values as list format, #rows and #columns, 
                    # here we assign those values! #row=2, #column=3 (meaning 2-by-3 matrix) VERY SMART
print(x)

[1] 1 2 3 4 5 6


NULL

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
